# Cloud Build configuration for Cloud Run deployment
# Triggered on push to main branch

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${_TAG}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:latest'
      - '.'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${_TAG}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '${PROJECT_ID}:${_REGION}:${_SQL_INSTANCE}'
      - '--memory'
      - '${_MEMORY}'
      - '--cpu'
      - '${_CPU}'
      - '--min-instances'
      - '${_MIN_INSTANCES}'
      - '--max-instances'
      - '${_MAX_INSTANCES}'
      - '--set-secrets'
      - 'DB_PASSWORD=db-password:latest,SESSION_SECRET=session-secret:latest'
      # Use --update-env-vars to PRESERVE existing env vars (like Zoho, AWS credentials)
      # Only update the base vars needed for the app to run
      - '--update-env-vars'
      - 'NODE_ENV=production,GCP_PROJECT_ID=${PROJECT_ID},GCS_BUCKET_NAME=${_BUCKET_NAME},DB_HOST=/cloudsql/${PROJECT_ID}:${_REGION}:${_SQL_INSTANCE},DB_USER=${_DB_USER},DB_NAME=${_DB_NAME}'

# Substitution variables (can be overridden)
# NOTE: Sensitive env vars (Zoho, AWS, EasyEcom) are set once via:
#   gcloud run services update kotty-track --region=asia-south1 --update-env-vars="..."
# They persist across deployments because we use --update-env-vars (not --set-env-vars)
substitutions:
  _REGION: 'asia-south1'
  _REPO_NAME: 'kotty-track'
  _SERVICE_NAME: 'kotty-track'
  _SQL_INSTANCE: 'kotty-mysql'
  _BUCKET_NAME: 'kotty-track-uploads'
  _DB_USER: 'kotty_user'
  _DB_NAME: 'kotty_db'
  _MEMORY: '1Gi'
  _CPU: '1'
  _MIN_INSTANCES: '0'
  _MAX_INSTANCES: '10'
  _TAG: 'v2'

# Store images in Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${_TAG}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:latest'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
